version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    depends_on:
      - message-service

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    restart: always

  message-service:
    build:
      context: ./message-service
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always