name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials (via OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::944331437251:role/github_deploy
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Save private key
      run: |
        echo "${{ steps.apply.outputs.private_key }}" > deployer-key.pem
        chmod 600 deployer-key.pem

    - name: Save private key as GitHub secret
      run: echo "PRIVATE_KEY=$(cat deployer-key.pem)" >> $GITHUB_ENV

    - name: Save EC2 public IP as GitHub secret
      run: |
        echo "EC2_PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV