name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::944331437251:role/github_deploy
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Destroy previous infrastructure
        run: terraform destroy -auto-approve

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Save private key to file
        run: |
          terraform output -raw private_key > deployer-key.pem
          chmod 600 deployer-key.pem

      - name: Export private key to env variable
        run: |
          echo "PRIVATE_KEY=$(cat deployer-key.pem)" >> $GITHUB_ENV

      - name: Get EC2 public IP and export
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "EC2_PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV